import type { SceneRule } from './scene-profile';

export const SCENE_RULES: SceneRule[] = [
  {
    id: 'bathroom-drain',
    category: 'bathroom-accessories',
    patterns: [/ralo/, /grelha/, /box/, /banheiro/, /chuveiro/],
    useCase: 'organizar e melhorar visualmente a área molhada',
    environment: 'banheiro contemporâneo ou box realista',
    sceneType: 'bathroom-lifestyle',
    style: 'clean premium, realista e funcional',
    lighting: 'luz natural suave com reflexos controlados',
    composition: 'close médio editorial mostrando contexto sem esconder o produto',
    placement: 'produto instalado ou posicionado no ponto de uso coerente',
    negativeSpace: 'terço superior ou lateral livre para headline',
    propsAllowed: ['toalha neutra', 'planta discreta', 'revestimento claro'],
    forbiddenContext: ['cozinha', 'quarto', 'uso fora de área molhada', 'água em situação impossível'],
  },
  {
    id: 'kitchen-organization',
    category: 'kitchen-organization',
    patterns: [/organizador/, /gaveta/, /despensa/, /porta tempero/, /escorredor/, /cozinha/],
    useCase: 'ganhar organização e reduzir poluição visual na cozinha',
    environment: 'cozinha organizada, bancada ou despensa realista',
    sceneType: 'kitchen-organization',
    style: 'lifestyle natural, claro e editorial',
    lighting: 'luz diurna suave e limpa',
    composition: 'produto como ponto focal com contexto suficiente para demonstrar uso',
    placement: 'produto em bancada, gaveta, armário ou despensa conforme sua função',
    negativeSpace: 'área superior esquerda ou direita com baixa informação visual',
    propsAllowed: ['utensílios neutros', 'potes simples', 'madeira clara', 'cerâmica'],
    forbiddenContext: ['banheiro', 'garagem', 'uso incompatível', 'excesso de alimentos ou props'],
  },
  {
    id: 'kitchen-utensils',
    category: 'kitchen-utensils',
    patterns: [/pote/, /panela/, /talher/, /utensil/, /tigela/, /copo/, /caneca/],
    useCase: 'facilitar preparo, armazenamento ou rotina da cozinha',
    environment: 'cozinha ou bancada doméstica elegante e realista',
    sceneType: 'kitchen-lifestyle',
    style: 'editorial cotidiano e natural',
    lighting: 'luz lateral suave, sem aparência de catálogo barato',
    composition: 'close médio com produto claramente reconhecível',
    placement: 'produto em uso passivo coerente na bancada',
    negativeSpace: 'faixa superior limpa para headline',
    propsAllowed: ['tecido neutro', 'madeira', 'ingredientes discretos'],
    forbiddenContext: ['uso industrial não comprovado', 'função não confirmada', 'marca alterada'],
  },
  {
    id: 'lighting',
    category: 'lighting',
    patterns: [/luminaria/, /abajur/, /lampada/, /pendente/, /led/],
    useCase: 'criar iluminação funcional ou aconchegante',
    environment: 'quarto, sala ou home office coerente com o produto',
    sceneType: 'ambient-lighting',
    style: 'aconchegante, premium e realista',
    lighting: 'luz contextual do próprio ambiente com contraste suave',
    composition: 'produto visível no contexto, sem estourar highlights',
    placement: 'posição natural de instalação ou apoio',
    negativeSpace: 'parede ou área sombreada livre para headline',
    propsAllowed: ['livros discretos', 'mesa lateral', 'texturas naturais'],
    forbiddenContext: ['brilho impossível', 'mudança de temperatura de cor como atributo', 'instalação incompatível'],
  },
  {
    id: 'rug-decor',
    category: 'home-decor',
    patterns: [/tapete/, /almofada/, /capa de sofa/, /cortina/, /decoracao/],
    useCase: 'melhorar conforto e composição visual do ambiente',
    environment: 'sala ou quarto residencial realista',
    sceneType: 'room-inspiration',
    style: 'editorial de interiores, sofisticado e habitável',
    lighting: 'luz natural difusa',
    composition: 'plano aberto controlado com produto legível no feed',
    placement: 'produto na posição residencial apropriada',
    negativeSpace: 'parede ou área de piso visualmente calma',
    propsAllowed: ['sofá neutro', 'mesa lateral', 'planta discreta'],
    forbiddenContext: ['luxo irreal', 'dimensão inventada', 'cor alterada'],
  },
  {
    id: 'laundry',
    category: 'laundry',
    patterns: [/lavanderia/, /cesto de roupa/, /varal/, /lavar/, /sabao/],
    useCase: 'organizar e facilitar a rotina de lavanderia',
    environment: 'lavanderia pequena, limpa e funcional',
    sceneType: 'laundry-utility',
    style: 'funcional, clean e realista',
    lighting: 'luz natural clara',
    composition: 'contexto compacto com foco na praticidade',
    placement: 'produto junto ao ponto de uso real',
    negativeSpace: 'faixa superior livre ou porta/parede limpa',
    propsAllowed: ['cesto neutro', 'toalhas dobradas', 'frascos sem marca'],
    forbiddenContext: ['cozinha', 'uso incompatível', 'claims de limpeza'],
  },
  {
    id: 'kids-room',
    category: 'kids-room',
    patterns: [/infantil/, /crianca/, /brinquedo/, /bebe/, /quarto infantil/],
    useCase: 'organizar ou compor um quarto infantil com segurança visual',
    environment: 'quarto infantil delicado e realista',
    sceneType: 'kids-room-lifestyle',
    style: 'delicado, seguro, natural e sem excesso visual',
    lighting: 'luz natural suave',
    composition: 'produto focal em ambiente calmo',
    placement: 'posição coerente e sem sugerir uso inseguro',
    negativeSpace: 'parede clara com respiro',
    propsAllowed: ['livros infantis genéricos', 'brinquedos simples', 'tecidos suaves'],
    forbiddenContext: ['situação de risco', 'criança reconhecível', 'claims de segurança não confirmados'],
  },
  {
    id: 'pet',
    category: 'pet',
    patterns: [/pet/, /cachorro/, /gato/, /comedouro/, /areia/, /coleira/],
    useCase: 'facilitar a rotina doméstica com pets',
    environment: 'casa real com contexto pet discreto',
    sceneType: 'pet-lifestyle',
    style: 'cotidiano natural, limpo e acolhedor',
    lighting: 'luz diurna suave',
    composition: 'produto claro, com contexto sem depender de animal em cena',
    placement: 'posição de uso doméstico coerente',
    negativeSpace: 'parede ou piso limpo para headline',
    propsAllowed: ['manta neutra', 'brinquedo pet simples', 'planta segura genérica'],
    forbiddenContext: ['benefício veterinário', 'animal em risco', 'função terapêutica'],
  },
  {
    id: 'office',
    category: 'home-office',
    patterns: [/escritorio/, /home office/, /mesa/, /suporte notebook/, /organizador de cabos/],
    useCase: 'organizar e melhorar a rotina de trabalho em casa',
    environment: 'home office moderno e funcional',
    sceneType: 'home-office',
    style: 'moderno, produtivo, premium e realista',
    lighting: 'luz lateral natural com contraste controlado',
    composition: 'mesa organizada com produto em destaque',
    placement: 'produto na posição normal de trabalho',
    negativeSpace: 'parede ou área de mesa limpa',
    propsAllowed: ['notebook genérico', 'caderno', 'caneta', 'planta discreta'],
    forbiddenContext: ['marca de computador inventada', 'setup impossível', 'ganho de produtividade garantido'],
  },
  {
    id: 'generic-home',
    category: 'home-utility',
    patterns: [/.*/],
    useCase: 'facilitar organização, conforto ou rotina doméstica',
    environment: 'ambiente residencial coerente com a função confirmada do produto',
    sceneType: 'home-lifestyle',
    style: 'natural, premium, editorial e realista',
    lighting: 'luz natural suave',
    composition: 'produto reconhecível com contexto controlado',
    placement: 'posição coerente com o uso confirmado',
    negativeSpace: 'uma área deliberadamente limpa para headline',
    propsAllowed: ['objetos domésticos neutros e discretos'],
    forbiddenContext: ['uso impossível', 'função não confirmada', 'marca ou cor alterada'],
  },
];
