export const FEATURE_FLAGS = {
  PINTEREST_API_ENABLED: false,
  PINTEREST_STANDARD_ACCESS: false,
  PINTEREST_AUTO_PUBLISH: false,
  PINTEREST_TRENDS_API: false,
  MELI_ENABLED: true,
  SHOPEE_ENABLED: true,
  AMAZON_ENABLED: false,
  GEMINI_FREE_ENABLED: false,
  OPENAI_API_ENABLED: false,
  OPENAI_IMAGE_ENABLED: false,
  OPENAI_EDIT_ENABLED: false,
  INTERNATIONAL_ENABLED: false,
  PAID_SERVICES_DISABLED: true,
} as const;

export const KILL_SWITCHES = {
  PAUSE_ALL_AUTOMATION: false,
  PINTEREST_PUBLISH_DISABLED: false,
  AI_DISABLED: false,
  MELI_DISABLED: false,
  SHOPEE_DISABLED: false,
  PAID_SERVICES_DISABLED: true,
} as const;

export function isPaidCapabilityAllowed() {
  return !FEATURE_FLAGS.PAID_SERVICES_DISABLED && !KILL_SWITCHES.PAID_SERVICES_DISABLED;
}
